// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_diag.proto

package sirup.service.diag.rpc.proto;

public interface DiagnosticsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:diag.v1.DiagnosticsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.diag.v1.Report report = 1;</code>
   */
  boolean hasReport();
  /**
   * <code>.diag.v1.Report report = 1;</code>
   */
  sirup.service.diag.rpc.proto.Report getReport();
  /**
   * <code>.diag.v1.Report report = 1;</code>
   */
  sirup.service.diag.rpc.proto.ReportOrBuilder getReportOrBuilder();
}
