// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_diag.proto

package sirup.service.diag.rpc.proto;

public interface DiagnosticsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:diag.v1.DiagnosticsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
