// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_diag.proto

package sirup.service.diag.rpc.proto;

public final class Diagnostics {
  private Diagnostics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_diag_v1_DiagnosticsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_diag_v1_DiagnosticsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_diag_v1_DiagnosticsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_diag_v1_DiagnosticsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_diag_v1_Report_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_diag_v1_Report_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_diag_v1_Vitals_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_diag_v1_Vitals_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020sirup_diag.proto\022\007diag.v1\"4\n\022Diagnosti" +
      "csRequest\022\r\n\005token\030\001 \001(\t\022\017\n\007user_id\030\002 \001(" +
      "\t\"6\n\023DiagnosticsResponse\022\037\n\006report\030\001 \001(\013" +
      "2\017.diag.v1.Report\")\n\006Report\022\037\n\006vitals\030\001 " +
      "\003(\0132\017.diag.v1.Vitals\"F\n\006Vitals\022\024\n\014servic" +
      "e_name\030\001 \001(\t\022\017\n\007running\030\002 \001(\010\022\025\n\rrespons" +
      "e_time\030\003 \001(\0032h\n\027SirupDiagnosticsService\022" +
      "M\n\016RunDiagnostics\022\033.diag.v1.DiagnosticsR" +
      "equest\032\034.diag.v1.DiagnosticsResponse\"\000B3" +
      "\n\034sirup.service.diag.rpc.protoB\013Diagnost" +
      "icsP\001\242\002\003SASb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_diag_v1_DiagnosticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_diag_v1_DiagnosticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_diag_v1_DiagnosticsRequest_descriptor,
        new java.lang.String[] { "Token", "UserId", });
    internal_static_diag_v1_DiagnosticsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_diag_v1_DiagnosticsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_diag_v1_DiagnosticsResponse_descriptor,
        new java.lang.String[] { "Report", });
    internal_static_diag_v1_Report_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_diag_v1_Report_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_diag_v1_Report_descriptor,
        new java.lang.String[] { "Vitals", });
    internal_static_diag_v1_Vitals_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_diag_v1_Vitals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_diag_v1_Vitals_descriptor,
        new java.lang.String[] { "ServiceName", "Running", "ResponseTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
