// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_diag.proto

package sirup.service.diag.rpc.proto;

/**
 * Protobuf type {@code diag.v1.Report}
 */
public  final class Report extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:diag.v1.Report)
    ReportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Report.newBuilder() to construct.
  private Report(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Report() {
    vitals_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Report(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              vitals_ = new java.util.ArrayList<sirup.service.diag.rpc.proto.Vitals>();
              mutable_bitField0_ |= 0x00000001;
            }
            vitals_.add(
                input.readMessage(sirup.service.diag.rpc.proto.Vitals.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        vitals_ = java.util.Collections.unmodifiableList(vitals_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sirup.service.diag.rpc.proto.Diagnostics.internal_static_diag_v1_Report_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sirup.service.diag.rpc.proto.Diagnostics.internal_static_diag_v1_Report_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sirup.service.diag.rpc.proto.Report.class, sirup.service.diag.rpc.proto.Report.Builder.class);
  }

  public static final int VITALS_FIELD_NUMBER = 1;
  private java.util.List<sirup.service.diag.rpc.proto.Vitals> vitals_;
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  public java.util.List<sirup.service.diag.rpc.proto.Vitals> getVitalsList() {
    return vitals_;
  }
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  public java.util.List<? extends sirup.service.diag.rpc.proto.VitalsOrBuilder> 
      getVitalsOrBuilderList() {
    return vitals_;
  }
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  public int getVitalsCount() {
    return vitals_.size();
  }
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  public sirup.service.diag.rpc.proto.Vitals getVitals(int index) {
    return vitals_.get(index);
  }
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  public sirup.service.diag.rpc.proto.VitalsOrBuilder getVitalsOrBuilder(
      int index) {
    return vitals_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < vitals_.size(); i++) {
      output.writeMessage(1, vitals_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < vitals_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, vitals_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sirup.service.diag.rpc.proto.Report)) {
      return super.equals(obj);
    }
    sirup.service.diag.rpc.proto.Report other = (sirup.service.diag.rpc.proto.Report) obj;

    boolean result = true;
    result = result && getVitalsList()
        .equals(other.getVitalsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVitalsCount() > 0) {
      hash = (37 * hash) + VITALS_FIELD_NUMBER;
      hash = (53 * hash) + getVitalsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sirup.service.diag.rpc.proto.Report parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.diag.rpc.proto.Report parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static sirup.service.diag.rpc.proto.Report parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static sirup.service.diag.rpc.proto.Report parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sirup.service.diag.rpc.proto.Report prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code diag.v1.Report}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:diag.v1.Report)
      sirup.service.diag.rpc.proto.ReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sirup.service.diag.rpc.proto.Diagnostics.internal_static_diag_v1_Report_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sirup.service.diag.rpc.proto.Diagnostics.internal_static_diag_v1_Report_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sirup.service.diag.rpc.proto.Report.class, sirup.service.diag.rpc.proto.Report.Builder.class);
    }

    // Construct using sirup.service.diag.rpc.proto.Report.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVitalsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (vitalsBuilder_ == null) {
        vitals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        vitalsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sirup.service.diag.rpc.proto.Diagnostics.internal_static_diag_v1_Report_descriptor;
    }

    @java.lang.Override
    public sirup.service.diag.rpc.proto.Report getDefaultInstanceForType() {
      return sirup.service.diag.rpc.proto.Report.getDefaultInstance();
    }

    @java.lang.Override
    public sirup.service.diag.rpc.proto.Report build() {
      sirup.service.diag.rpc.proto.Report result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sirup.service.diag.rpc.proto.Report buildPartial() {
      sirup.service.diag.rpc.proto.Report result = new sirup.service.diag.rpc.proto.Report(this);
      int from_bitField0_ = bitField0_;
      if (vitalsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          vitals_ = java.util.Collections.unmodifiableList(vitals_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.vitals_ = vitals_;
      } else {
        result.vitals_ = vitalsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sirup.service.diag.rpc.proto.Report) {
        return mergeFrom((sirup.service.diag.rpc.proto.Report)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sirup.service.diag.rpc.proto.Report other) {
      if (other == sirup.service.diag.rpc.proto.Report.getDefaultInstance()) return this;
      if (vitalsBuilder_ == null) {
        if (!other.vitals_.isEmpty()) {
          if (vitals_.isEmpty()) {
            vitals_ = other.vitals_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVitalsIsMutable();
            vitals_.addAll(other.vitals_);
          }
          onChanged();
        }
      } else {
        if (!other.vitals_.isEmpty()) {
          if (vitalsBuilder_.isEmpty()) {
            vitalsBuilder_.dispose();
            vitalsBuilder_ = null;
            vitals_ = other.vitals_;
            bitField0_ = (bitField0_ & ~0x00000001);
            vitalsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVitalsFieldBuilder() : null;
          } else {
            vitalsBuilder_.addAllMessages(other.vitals_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      sirup.service.diag.rpc.proto.Report parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (sirup.service.diag.rpc.proto.Report) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<sirup.service.diag.rpc.proto.Vitals> vitals_ =
      java.util.Collections.emptyList();
    private void ensureVitalsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        vitals_ = new java.util.ArrayList<sirup.service.diag.rpc.proto.Vitals>(vitals_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        sirup.service.diag.rpc.proto.Vitals, sirup.service.diag.rpc.proto.Vitals.Builder, sirup.service.diag.rpc.proto.VitalsOrBuilder> vitalsBuilder_;

    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public java.util.List<sirup.service.diag.rpc.proto.Vitals> getVitalsList() {
      if (vitalsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(vitals_);
      } else {
        return vitalsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public int getVitalsCount() {
      if (vitalsBuilder_ == null) {
        return vitals_.size();
      } else {
        return vitalsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public sirup.service.diag.rpc.proto.Vitals getVitals(int index) {
      if (vitalsBuilder_ == null) {
        return vitals_.get(index);
      } else {
        return vitalsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder setVitals(
        int index, sirup.service.diag.rpc.proto.Vitals value) {
      if (vitalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVitalsIsMutable();
        vitals_.set(index, value);
        onChanged();
      } else {
        vitalsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder setVitals(
        int index, sirup.service.diag.rpc.proto.Vitals.Builder builderForValue) {
      if (vitalsBuilder_ == null) {
        ensureVitalsIsMutable();
        vitals_.set(index, builderForValue.build());
        onChanged();
      } else {
        vitalsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder addVitals(sirup.service.diag.rpc.proto.Vitals value) {
      if (vitalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVitalsIsMutable();
        vitals_.add(value);
        onChanged();
      } else {
        vitalsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder addVitals(
        int index, sirup.service.diag.rpc.proto.Vitals value) {
      if (vitalsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVitalsIsMutable();
        vitals_.add(index, value);
        onChanged();
      } else {
        vitalsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder addVitals(
        sirup.service.diag.rpc.proto.Vitals.Builder builderForValue) {
      if (vitalsBuilder_ == null) {
        ensureVitalsIsMutable();
        vitals_.add(builderForValue.build());
        onChanged();
      } else {
        vitalsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder addVitals(
        int index, sirup.service.diag.rpc.proto.Vitals.Builder builderForValue) {
      if (vitalsBuilder_ == null) {
        ensureVitalsIsMutable();
        vitals_.add(index, builderForValue.build());
        onChanged();
      } else {
        vitalsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder addAllVitals(
        java.lang.Iterable<? extends sirup.service.diag.rpc.proto.Vitals> values) {
      if (vitalsBuilder_ == null) {
        ensureVitalsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, vitals_);
        onChanged();
      } else {
        vitalsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder clearVitals() {
      if (vitalsBuilder_ == null) {
        vitals_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        vitalsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public Builder removeVitals(int index) {
      if (vitalsBuilder_ == null) {
        ensureVitalsIsMutable();
        vitals_.remove(index);
        onChanged();
      } else {
        vitalsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public sirup.service.diag.rpc.proto.Vitals.Builder getVitalsBuilder(
        int index) {
      return getVitalsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public sirup.service.diag.rpc.proto.VitalsOrBuilder getVitalsOrBuilder(
        int index) {
      if (vitalsBuilder_ == null) {
        return vitals_.get(index);  } else {
        return vitalsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public java.util.List<? extends sirup.service.diag.rpc.proto.VitalsOrBuilder> 
         getVitalsOrBuilderList() {
      if (vitalsBuilder_ != null) {
        return vitalsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(vitals_);
      }
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public sirup.service.diag.rpc.proto.Vitals.Builder addVitalsBuilder() {
      return getVitalsFieldBuilder().addBuilder(
          sirup.service.diag.rpc.proto.Vitals.getDefaultInstance());
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public sirup.service.diag.rpc.proto.Vitals.Builder addVitalsBuilder(
        int index) {
      return getVitalsFieldBuilder().addBuilder(
          index, sirup.service.diag.rpc.proto.Vitals.getDefaultInstance());
    }
    /**
     * <code>repeated .diag.v1.Vitals vitals = 1;</code>
     */
    public java.util.List<sirup.service.diag.rpc.proto.Vitals.Builder> 
         getVitalsBuilderList() {
      return getVitalsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        sirup.service.diag.rpc.proto.Vitals, sirup.service.diag.rpc.proto.Vitals.Builder, sirup.service.diag.rpc.proto.VitalsOrBuilder> 
        getVitalsFieldBuilder() {
      if (vitalsBuilder_ == null) {
        vitalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            sirup.service.diag.rpc.proto.Vitals, sirup.service.diag.rpc.proto.Vitals.Builder, sirup.service.diag.rpc.proto.VitalsOrBuilder>(
                vitals_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        vitals_ = null;
      }
      return vitalsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:diag.v1.Report)
  }

  // @@protoc_insertion_point(class_scope:diag.v1.Report)
  private static final sirup.service.diag.rpc.proto.Report DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sirup.service.diag.rpc.proto.Report();
  }

  public static sirup.service.diag.rpc.proto.Report getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Report>
      PARSER = new com.google.protobuf.AbstractParser<Report>() {
    @java.lang.Override
    public Report parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Report(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Report> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Report> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sirup.service.diag.rpc.proto.Report getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

