// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_diag.proto

package sirup.service.diag.rpc.proto;

public interface ReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:diag.v1.Report)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  java.util.List<sirup.service.diag.rpc.proto.Vitals> 
      getVitalsList();
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  sirup.service.diag.rpc.proto.Vitals getVitals(int index);
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  int getVitalsCount();
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  java.util.List<? extends sirup.service.diag.rpc.proto.VitalsOrBuilder> 
      getVitalsOrBuilderList();
  /**
   * <code>repeated .diag.v1.Vitals vitals = 1;</code>
   */
  sirup.service.diag.rpc.proto.VitalsOrBuilder getVitalsOrBuilder(
      int index);
}
