// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sirup_diag.proto

package sirup.service.diag.rpc.proto;

public interface VitalsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:diag.v1.Vitals)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_name = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>bool running = 2;</code>
   */
  boolean getRunning();

  /**
   * <code>int64 response_time = 3;</code>
   */
  long getResponseTime();
}
